version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd todo-app
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build

artifacts:
  files:
    - '**/*'
    #- "todo-app/build/**/*"
  base-directory: 'todo-app/build'
  #discard-paths: yes